### ISSUE TITLE
Error when activated without workspace (folder) open

### ISSUE THREAD

**Issue by bartosz-antosik** [alefragnani/vscode-bookmarks#94]
Hi! When I start VSCode WITHOUT workspace (e.g. by performing `File` -> `Close Folder` bookmarks fails during activate. Here is what is thrown to debug console:

Activating extension `alefragnani.Bookmarks` failed: Cannot read property '0' of undefined.
Activating extension `alefragnani.Bookmarks` failed:  Cannot read property '0' of undefined
Here is the error stack:  TypeError: Cannot read property '0' of undefined
	at loadWorkspaceState (C:\Users\ban.necne\.vscode\extensions\alefragnani.bookmarks-0.18.1 \out\src\extension.js:705:85)
	at activate (C:\Users\ban.necne\.vscode\extensions\alefragnani.bookmarks-0.18.1\out\src\extension.js:17:28)
	at Function.t._callActivateOptional (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:688:725)
	at Function.t._callActivate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:688:409)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:687:572
	at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:68:868)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:153)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:73:970)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:73:411)
	at c (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:76:888)

**Comment by alefragnani** [comment]
Hi @bartosz-antosik ,

I could reproduce this log, but I didn't get any error in VS Code notification area. Did you get any?

Thanks

**Comment by bartosz-antosik** [comment]
Yes I do get a notification:

![image](https://user-images.githubusercontent.com/20492548/36641088-b3496c18-1a2a-11e8-9dcc-b7a13dc6918a.png)

But ONLY when I start VSCode as Extension Developement Host (that is when I debug my extension). When I do the same in the only opened VSCode it does not happen! Sorry I haven't noticed this duality!

**Comment by alefragnani** [comment]
Thanks. That's probably the reason I didn't see this issue 😄
